---
title: 309
output:
  flexdashboard::flex_dashboard:
    theme:
      version: 3  #<< set to 3, 4, 5, ...
    orientation: row
params:
  bs_version: ""
runtime: shiny
---

Page 1 {data-test-id="Page 1"}
===================================

## Box 1-1 {.tabset data-test-id="Box 1-1"}

### Tab 1-1a {data-test-id="Tab 1-1a"}

**About this test**: This app tests our usage of Bootstrap's Tab plugin.
Test this app in all major versions of Bootstrap.

1. Change the active tabs on this page.
2. Switch to Page 2 under "Other"
3. Switch to Page 3 under "Other"

Verify that only the expected pages are visible
and that the active navbar menu state is correctly shown.

This is Bootstrap `r params$bs_version`.

### Tab 1-1b {data-test-id="Tab 1-1b"}

Tab content, page 1, box 1, tab b

## Box 1-2 {.tabset data-test-id="Box 1-2"}

### Tab 1-2a {data-test-id="Tab 1-2a"}

Tab content, page 1, box 2, tab a

### Tab 1-2b {data-test-id="Tab 1-2b"}

Tab content, page 1, box 2, tab b


Page 2 {data-navmenu="Other" data-test-id="Page 2"}
===================================

## Row

### Box 2-1 {data-test-id="Box 2-1"}

Content, page 2, box 1

### Box 2-2 {data-test-id="Box 2-2"}

Content, page 2, box 2


Page 3 {data-navmenu="Other" data-test-id="Page 3"}
===================================

## Row

### Box 3-1 {data-test-id="Box 3-1"}

Content, page 3, box 1

### Box 3-2 {data-test-id="Box 3-2"}

Content, page 3, box 2
