---
title: '`r paste0("rstudio/shinycoreci results:<br/>", params$start_date, " - ", params$end_date)`'
output:
  html_document:
    mathjax: NULL
    self_contained: false
    theme: !expr bslib::bs_add_rules(bslib::bs_theme(base_font = bslib::font_google("Prompt")), ".nav-pills { @extend .justify-content-center; }")
params:
  start_date: "DATE"
  end_date: "DATE"
  df: "tbl"
---

```{r, echo = FALSE, include = TRUE}
# shiny::dateInput("datepicker", "Date", params$end_date)
# shinyWidgets::airDatepickerInput("datepicker", "Date", value = params$end_date)
library(shiny)
tagList(
  # fontawesome::fa("calendar"),
  shiny::dateInput("datepicker", fontawesome::fa("calendar"), params$end_date, width = "fit-content"),
  tags$script(HTML(paste0("
    $(function() {
      var d = '", params$end_date, "';
      $('#datepicker').find(\"input\").bsDatepicker(\"setUTCDate\", new Date(d));
      $('#datepicker').find(\"input\").change(function() {
        var new_date = $(this).val();
        window.location = '../../../' + new_date.replaceAll('-', '/') + '/index.html';
      })
    });
  ")))

)
```


```{css, echo=FALSE}
#datepicker {
  display: flex;
  gap: 1rem;
  position: absolute;
  top: 5px;
  right: 5px;
}
#datepicker input {
  width: 8rem;
}
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
.dataTables_filter {display: none};
.result_app {padding: 0.5em; border-collapse: collapse;}
.result_pass {background-color: #009469 !important;} /* green */
.result_fail {
  background-color: #d95515 !important; /* red */
  cursor: pointer;
}
.result_can_not_install {background-color: #0066a7 !important;} /* blue */
.result_did_not_return {background-color: #a3a3a3 !important;} /* white */
.result_did_not_execute {background-color: #323232 !important;} /* black */
.result_day td {
  border: 1px dotted grey;
  padding: 0.5rem !important;
  border-radius: 50%;
  /* No border */
}
.result_day {
  border-spacing: 1px;
  border-collapse: separate;
}
.result_app > tbody > tr > td {
    padding: 0px !important;
    padding-right: 6px !important;
}

.no-failures {
  color:darkgreen;
}
.has-failures {
  color:darkred;
}

/* Reduce title height */
.form-group {
  margin-bottom: 0 !important;
}
.selectize-control {
  margin-bottom: 0 !important;
}
```

```{r, echo = FALSE, include = TRUE}
render_rest <- TRUE
if (nrow(params$df) == 0) {
  h1("No results found. Please pick another date.")
  render_rest <- FALSE
}
```


```{r, include = FALSE}
library(dplyr)
library(tidyr)
library(magrittr)
library(shiny)

logs <- params$df %>% unnest(results)
logs_spread <-
  logs %>%
    count(app_name, os, r_version, date, status, name = "n") %>%
    spread(status, n, fill = 0)

# Order by fail count
if ("fail" %in% names(logs_spread)) {
  logs_spread <- arrange(logs_spread, desc(fail))
}

# Add in missing columns
for (nme in c("can_not_install", "did_not_return_result", "fail", "pass")) {
  if (!rlang::has_name(logs_spread, nme)) {
    logs_spread[[nme]] <- 0
  }
}

logs_spread <- logs_spread %>%
  complete(
    app_name, os, r_version, date,
    fill = list(
      can_not_install = 0,
      did_not_return_result = 0,
      fail = 0,
      pass = 0
    )
  ) %>%
  mutate(
    not_executed = as.numeric(pass == 0 & fail == 0 & can_not_install == 0 & did_not_return_result == 0)
  )
```

```{r redirect, echo = FALSE, include = TRUE}
logs_spread_today <-
  logs_spread %>%
  filter(date == params$end_date)

if (nrow(logs_spread_today) == 0) {
  render_rest <- FALSE
  last_day_with_results <- max(logs_spread$date)

  url_with_results <-
    paste0(
      strsplit(as.character(last_day_with_results), "-")[[1]],
      collapse = "/"
    )
  href_with_results <- paste0("../../../", url_with_results, "/index.html")

  tagList(
    tags$h1(
      "Refreshing to prior day with results: ",
      a(href = href_with_results, last_day_with_results)
    ),
    tags$meta(
      "http-equiv" = "Refresh",
      content = paste0("3; url=", href_with_results)
    )
  )
}
```

```{r logs_summary, include = FALSE}
logs_summary_today <-
  logs_spread %>%
  filter(date == params$end_date) %>%
  group_by(app_name) %>%
  summarise(
    fail = sum(fail),
    pass = sum(pass),
    can_not_install = sum(can_not_install),
    did_not_return_result = sum(did_not_return_result),
    not_executed = sum(not_executed)
  )
logs_summary_total <-
  logs_spread %>%
  group_by(app_name) %>%
  summarise(
    fail_total = sum(fail),
    pass_total = sum(pass),
    can_not_install_total = sum(can_not_install),
    did_not_return_result_total = sum(did_not_return_result),
    not_executed_total = sum(not_executed)
  )
logs_summary <-
  left_join(
    logs_summary_today,
    logs_summary_total,
    by = c("app_name" = "app_name")
  )
  #  %>%
  # select(
  #   app_name,
  #   fail,
  #   pass,
  #   can_not_install,
  #   did_not_return_result,
  #   not_executed,
  #   fail_total,
  #   pass_total,
  #   can_not_install_total,
  #   did_not_return_result_total,
  #   not_executed_total
  # )
```

```{r logs_details, include = FALSE}
logs_details <-
  logs_spread %>%
  mutate(
    cell_class = unlist(Map(
      pass, fail, can_not_install, did_not_return_result, not_executed,
      f = function(
        pass_, fail_, can_not_install_, did_not_return_result_, not_executed_
      ) {
        if (fail_ > 0) return("result_fail")
        if (pass_ > 0) return("result_pass")
        if (can_not_install_ > 0) return("result_can_not_install")
        if (did_not_return_result_ > 0) return("result_did_not_return_result")
        if (not_executed_ > 0) return("result_did_not_execute")
        str(list(
          fail_ = fail_,
          pass_ = pass_,
          can_not_install_ = can_not_install_,
          did_not_return_result_ = did_not_return_result_,
          not_executed_ = not_executed_
        ))
        stop("unknown state")
      }
    )),
    cell_status = c(
      "result_fail" = "Fail",
      "result_pass" = "Pass",
      "result_can_not_install" = "Could not install",
      "result_did_not_return_result" = "Did not test (ok)",
      "result_did_not_execute" = "Test did not execute (bad)"
    )[cell_class]
  ) %>%
  # platform is horizontal
  group_by(app_name, date, r_version) %>%
  arrange(os, desc(r_version)) %>%
  summarise(
    .groups = "keep",
    rows = {
      list(do.call(
        tags$tr,
        Map(
          date, os, r_version, cell_status, cell_class,
          f = function(
            date_, os_, r_version_, cell_status_, cell_class_
          ) {
            tag_location <-
              strsplit(as.character(date), "-")[[1]] %>%
              paste0(collapse = "/") %>%
              paste0("../../../", ., "/index.html#", app_name[[1]], "-", os_, "-", r_version_)

            tags$td(
              class = "result_cell",
              "data-toggle" = "tooltip",
              "data-html" = "true",
              onclick = paste0("window.location = '", tag_location, "';"),
              title = paste0(os_, " ", r_version_, " - ", date_, " ", cell_status_),
              class = cell_class_
            )
          }
        )
      ))
    }
  ) %>%
  group_by(app_name, date) %>%
  arrange(desc(r_version)) %>%
  summarise(
    per_date = {
      list(
        tags$table(rows, class = "result_day")
      )
    },
    .groups = "keep"
  ) %>%
  group_by(app_name) %>%
  arrange(date) %>%
  summarise(
    performance = {
      list(
        tags$table(
          class = "result_app",
          tags$tr(
            lapply(per_date, tags$td)
          )
        )
      )
    },
    .groups = "keep"
  )
```

```{r bad_logs, include = FALSE}
bad_logs <-
  logs %>%
  filter(date == params$end_date) %>%
  filter(
    status %in% c("fail", "can_not_install")
  ) %>%
  arrange(app_name)

bad_app_tags <-
  lapply(unique(bad_logs$app_name), function(bad_app_name) {
    bad_app_logs <-
      bad_logs %>%
      filter(app_name == bad_app_name)

    ## Never hit!
    # if (nrow(bad_app_logs) == 0) {
    #   browser()
    #   return(paste0(
    #     "No failures to show for ", bad_app_name, " on ", params$end_date
    #   ))
    # }

    bad_display_logs_list <-
      bad_app_logs %>%
      split(., .$platform)

    bad_reports <- Map(
      bad_display_logs_list, names(bad_display_logs_list),
      f = function(display_logs, platform) {
        res <- paste(display_logs$result, collapse = "\n")
        id <- paste0(
          display_logs$app_name[[1]],
          "-",
          display_logs$os[[1]],
          "-",
          display_logs$r_version[[1]]
        )
        tags$details(
          open = NA,
          tags$summary(platform, id = id),
          tags$code(tags$pre(res))
        )
      }
    )

    tagList(
      tags$h3(bad_app_name, id = bad_app_name),
      # bad_app_plot,
      !!!bad_reports
    )
  })
```


```{r logs_combined, include = FALSE}
bad_app_names <- unique(bad_logs$app_name)
logs_combined <-
  left_join(
    logs_summary,
    logs_details,
    by = c("app_name" = "app_name")
  ) %>%
  select(app_name, performance, everything()) %>%
  mutate(
    app_name = lapply(app_name, function(app_name_val) {
      if (app_name_val %in% bad_app_names) {
        tags$a(
          href = paste0("#", app_name_val),
          class = "has-failures",
          app_name_val
        )
      } else {
        span(class = "no-failures", app_name_val)
      }
    })
  ) %>%
  mutate(
    app_name = lapply(app_name, function(x) HTML(as.character(x))),
    performance = lapply(performance, function(x) HTML(as.character(x)))
  ) %>%
  rename(
    App = app_name,
    Performance = performance,
    Fail = fail,
    Pass = pass,
    "Can't install" = can_not_install,
    "Skip test" = did_not_return_result,
    "Not exec" = not_executed,
    "Total fail" = fail_total,
    "Total pass" = pass_total,
    "Total can't install" = can_not_install_total,
    "Total skip test" = did_not_return_result_total,
    "Total not exec" = not_executed_total
  )
```

```{r data_table, echo = FALSE, include = TRUE}
if (render_rest && nrow(logs_combined) >= 0) {
  DT::datatable(
    logs_combined,
    rownames = FALSE,
    selection = "single",
    filter = "top",
    fillContainer = TRUE,
    # shrink if too skinny
    # extensions = c("Responsive", "FixedHeader"),
    options = list(
      # fixedHeader = TRUE,
      autoWidth = TRUE,
      columnDefs = list(list(width = '30px', targets = seq(2, ncol(logs_combined) - 1))),

      info = FALSE, paging = FALSE, #searching = FALSE,
      scrollY = "80vh",
      order = list(list(2, 'desc'), list(7, 'desc'), list(0, 'asc')),

      # Init the tooltips
      drawCallback =  htmlwidgets::JS("
        function() {
          $('td[data-toggle=\"tooltip\"]').tooltip({
            // animated: 'fade',
          });
        }
      ")
    ),
    # Be able to use raw html
    escape = FALSE
  )
}
```

```{r, eval = TRUE, echo = FALSE}
if (render_rest) {
  tagList(
    tags$h1("Failure logs:"),
    # selectInput(
    #   "logs_date", NULL,
    #   choices = sort(unique(logs$date), decreasing = TRUE)
    # ),
    !!!bad_app_tags
  )
}
```

```{r, eval = FALSE, include = FALSE}
  selected_app <- reactive({
    cell <- input$app_status_table_cell_clicked
    if (length(cell) > 0) {
      logs_summary()[cell$row, "App", drop = TRUE]
    }
  })

  app_logs <- reactive({
    req(selected_app())

    filter(
      logs(),
      app_name %in% selected_app(),
      status %in% c("fail", "can_not_install")
    )
  })

  selected_app_logs <- reactive({
    req(input$logs_date)
    filter(app_logs(), date == as.Date(input$logs_date))
  })

  observeEvent(input$app_status_table_cell_clicked, {

    logs <- app_logs()
    log_dates <- sort(unique(logs$date), decreasing = TRUE)

    # TODO: save GHA job id and create a hyperlink to
    # https://github.com/rstudio/shinycoreci-apps/runs/{job_id}
    # Better yet, can we link to either the build log or test source code?
    modal <- modalDialog(
      title = paste(selected_app(), "failure details"),
      size = "l",
      easyClose = TRUE,
      tabsetPanel(
        tabPanel(
          "Daily details",
          div(
            style = "display:flex; justify-content:center; gap:1rem",
            "Failure logs from:",
            selectInput(
              "logs_date", NULL, choices = log_dates
            )
          ),
          uiOutput("logs_report")
        ),
        tabPanel("Timeline", uiOutput("timeline")),
        type = "pills",
        header = br()
      )
    )

    showModal(modal)
  })

  output$timeline <- renderUI({
    validate(need(
      nrow(app_logs()) > 1,
      "No failures to show for this app"
    ))

    withr::with_namespace(
      "plotly", {

        panel <- . %>%
          plot_ly(height = 700) %>%
          add_bars(
            x = ~date, y = ~n, color = ~paste("R", r_version),
            legendgroup = ~r_version,
            showlegend = ~identical(unique(os), "Linux")
          ) %>%
          add_annotations(
            text = ~unique(os), showarrow = FALSE,
            x = 0.5, y = 1, yref = "paper", xref = "paper",
            yanchor = "bottom", font = list(size = 15),
            yshift = -3
          ) %>%
          layout(
            showlegend = FALSE,
            barmode = "stack",
            shapes = list(
              type = "rect",
              x0 = 0, x1 = 1, xref = "paper",
              y0 = 0, y1 = 16, yref = "paper",
              yanchor = 1, ysizemode = "pixel",
              fillcolor = toRGB("gray80"),
              line = list(color = "transparent")
            )
          )

        app_logs() %>%
          count(date, platform) %>%
          separate(platform, c("os", "r_version"), sep = "-") %>%
          group_by(os) %>%
          do(p = panel(.)) %>%
          subplot(nrows = NROW(.), shareX = TRUE) %>%
          layout(
            font = list(family = "Prompt", size = 14),
            showlegend = TRUE, hovermode = "x",
            yaxis2 = list(title = "Number of failures"),
            xaxis = list(title = ""),
            legend = list(orientation = "h", x = 1, xanchor = "right")
          ) %>%
          config(displayModeBar = FALSE)
      }
    )
  })

  output$logs_report <- renderUI({
    req(input$logs_date)

    logs <- selected_app_logs()
    logs <- split(logs, logs$platform)

    tagList(
      !!!Map(
        logs, names(logs),
        f = function(x, y) {
          res <- paste(x$result, collapse = "\n")
          tags$details(
            open = NA,
            tags$summary(y),
            tags$code(tags$pre(res))
          )
        }
      )
    )
  })

}

    if (FALSE) {
      bad_app_plot <-
        suppressWarnings(withr::with_namespace(
          "plotly",
          {
            panel <- . %>%
              plot_ly(height = 700) %>%
              add_bars(
                x = ~date, y = ~n, color = ~ paste("R", r_version),
                legendgroup = ~r_version,
                showlegend = ~ identical(unique(os), "Linux")
              ) %>%
              add_annotations(
                text = ~ unique(os), showarrow = FALSE,
                x = 0.5, y = 1, yref = "paper", xref = "paper",
                yanchor = "bottom", font = list(size = 15),
                yshift = -3
              ) %>%
              layout(
                showlegend = FALSE,
                barmode = "stack",
                shapes = list(
                  type = "rect",
                  x0 = 0, x1 = 1, xref = "paper",
                  y0 = 0, y1 = 16, yref = "paper",
                  yanchor = 1, ysizemode = "pixel",
                  fillcolor = toRGB("gray80"),
                  line = list(color = "transparent")
                )
              )

            bad_app_logs %>%
              count(date, platform) %>%
              separate(platform, c("os", "r_version"), sep = "-") %>%
              group_by(os) %>%
              do(p = panel(.)) %>%
              subplot(nrows = NROW(.), shareX = TRUE) %>%
              layout(
                font = list(family = "Prompt", size = 14),
                showlegend = TRUE, hovermode = "x",
                yaxis2 = list(title = "Number of failures"),
                xaxis = list(title = ""),
                legend = list(orientation = "h", x = 1, xanchor = "right")
              ) %>%
              config(displayModeBar = FALSE)
          }
        ))
    }


# shinyApp(ui, server)
```
