name: 'Install shinyverse packages'
description: 'Installs everything in a single pak installation step. Meant to work cross platform and R version'
author: 'Barret Schloerke'
inputs:
  r-version:
    description: R version to install
    default: release
    required: false
  extra-packages:
    description: Extra packages to install
    default: ""
    required: false
  cache-version:
    description: Cache version key to pass through
    default: "2"
    required: false
  http-user-agent:
    description: User agent to pass through
    default: ""
    required: false
  pandoc-version:
    description: Pandoc version to pass through
    default: "3.x"
    required: false
runs:
  using: "composite"
  steps:
    - name: Install Chinese fonts on Linux
      if: runner.os == 'Linux'
      shell: bash
      # https://unix.stackexchange.com/a/548473
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-arphic-ukai fonts-arphic-uming

    - name: Install system dependencies for igraph
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libglpk-dev

    - name: Install R and shinycoreci
      uses: rstudio/shiny-workflows/setup-r-package@v1
      with:
        r-version: ${{ inputs.r-version }}
        cache-version: ${{ inputs.cache-version }}
        http-user-agent: ${{ inputs.http-user-agent }}
        pandoc-version: ${{ inputs.pandoc-version }}
        extra-packages: ${{ inputs.extra-packages }}
        pak-version: "devel"

    - name: Get packages for macOS system dependencies
      if: runner.os == 'macOS'
      id: mac-deps
      shell: Rscript {0}
      run: |
        deps <- setdiff(
          sort(unique(unlist(unname(shinycoreci:::apps_deps_map)))),
          shinycoreci:::shinyverse_pkgs
        )
        cat("Deps found:\n", paste0("* ", deps, collapse = "\n"), "\n", sep = "")

        out_deps <- paste0(deps, collapse = " ")
        cat("pkgs=", out_deps, "\n", file = Sys.getenv("GITHUB_OUTPUT"), sep = "", append = TRUE)

    - name: Install mac system dependencies for app packages
      if: runner.os == 'macOS'
      uses: rstudio/shiny-workflows/setup-macOS-dependencies@v1
      with:
        extra-packages: ${{ steps.mac-deps.outputs.pkgs }} Cairo FreeType RMySQL textshaping units
