library(shinytest2)

test_that("Migrated shinytest test: mytest.R", {
  app <- AppDriver$new(variant = shinytest2::platform_variant(),
    seed = 100, shiny_args = list(display.mode = "normal"))
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(dist = "unif")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(dist = "lnorm")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(dist = "exp")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(dist = "norm")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(n = 1)
  app$set_inputs(n = 1000)
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(n = 1)
  app$set_inputs(n = 107)
  app$set_inputs(n = 1)
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(n = 511)
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(n = 896)
  app$expect_values()
  app$expect_screenshot()
})
