app <- ShinyDriver$new("../../", loadTimeout = 15000, seed = 100, shinyOptions = list(display.mode = "normal"))
print(app$getDebugLog())
cat('\n\n')
app$snapshotInit("mytest")
print(app$getDebugLog())
cat('\n\n')
app$snapshotDownload("download")
print(app$getDebugLog())
cat('\n\n')
app$setInputs(throw = TRUE)
print(app$getDebugLog())
cat('\n\n')
app$snapshotDownload("download")
print(app$getDebugLog())
cat('\n\n')
Sys.sleep(4)
app$snapshot()
print(app$getDebugLog())
cat('\n\n')
