library(shinytest2)

test_that("Migrated shinytest test: mytest.R", {
  app <- AppDriver$new(variant = shinytest2::platform_variant())

  app$wait_for_value(output = "observeEventStatus")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(type = "silent")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(type = "validation")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(type = "error")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(success = "click")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(silent = "click")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(validation = "click")
  app$expect_values()
  app$expect_screenshot()
})
