if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
if (!requireNamespace("yaml", quietly = TRUE)) install.packages("yaml")

update_renv_pkgs <- function(repo_dir = ".") {
  renv_pkgs <- sort(unique(renv::dependencies(
    file.path(repo_dir, "inst", "apps"),
    progress = TRUE
  )$Package))

  renv_pkgs <- setdiff(
    renv_pkgs,
    base_packages()
  )

  renv_pkgs_txt <- utils::capture.output(dput(renv_pkgs))

  cat(
    file = file.path(repo_dir, "R/data-renv-pkgs.R"),
    sep = "",
    "# Do not edit by hand!\n",
    "# This file is automatically generated by `./inst/gha/data-renv-pkgs-update.R`\n",
    "renv_pkgs <- ", paste0(renv_pkgs_txt, collapse = "\n"), "\n"
  )
}

base_packages <- function() {
  pkg_df <- as.data.frame(utils::installed.packages(), stringsAsFactors = FALSE)
  pkg_df$Package[pkg_df$Priority %in% c("base", "recommended")]
}
