if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
if (!requireNamespace("yaml", quietly = TRUE)) install.packages("yaml")
if (!requireNamespace("withr", quietly = TRUE)) install.packages("withr")

update_apps_deps <- function(repo_dir = ".") {
  withr::local_dir(repo_dir)

  source("R/data-shinyverse.R")
  revdeps <- renv::dependencies(
    "inst/apps",
    progress = TRUE
  )
  revdeps <-
    subset(
      revdeps,
      !(
        Package %in% c(base_packages(), "shinycoreci", shinyverse_pkgs)
      )
    )
  apps_deps <- sort(unique(revdeps$Package))

  revdeps$folder <- sub(".*/apps/(\\d\\d\\d-[^/]+)/.*", "\\1", revdeps$Source)

  apps_deps_map <- lapply(split(revdeps, revdeps$folder), function(revdeps_sub) {
    sort(unique(revdeps_sub$Package))
  })

  apps_deps_txt <- utils::capture.output(dput(apps_deps))
  apps_deps_map_txt <- utils::capture.output(dput(apps_deps_map))

  cat(
    file = file.path(repo_dir, "R/data-apps-deps.R"),
    sep = "",
    "# Do not edit by hand!\n",
    "# This file is automatically generated by `./inst/gha/data-apps-deps-update.R`\n",
    "apps_deps <- ", paste0(apps_deps_txt, collapse = "\n"), "\n",
    "apps_deps_map <- ", paste0(apps_deps_map_txt, collapse = "\n"), "\n"
  )
}

base_packages <- function() {
  pkg_df <- as.data.frame(utils::installed.packages(), stringsAsFactors = FALSE)
  pkg_df$Package[pkg_df$Priority %in% c("base", "recommended")]
}
