update_connect_urls <- function(
  apps = apps_shiny,
  account = "barret",
  server = "beta.rstudioconnect.com",
  repo_dir = "."
) {

  urls <- shinycoreci::connect_urls(apps = apps, account = account, server = server)

  urls_txt <- utils::capture.output(dput(urls))

  cat(
    file = file.path(repo_dir, "R/data-connect-urls.R"),
    sep = "",
    "# Do not edit by hand!\n",
    "# This file is automatically generated by `./R/data-connect-urls-update.R`\n",
    "default_connect_urls <- ", paste0(urls_txt, collapse = "\n"), "\n"
  )
}
