if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
if (!requireNamespace("yaml", quietly = TRUE)) install.packages("yaml")

update_apps_deps <- function(repo_dir = ".") {
  apps_deps <- sort(unique(renv::dependencies(
    file.path(repo_dir, "inst", "apps"),
    progress = TRUE
  )$Package))

  apps_deps <- setdiff(
    apps_deps,
    base_packages()
  )

  source("R/data-shinyverse.R")
  apps_deps <- setdiff(
    apps_deps,
    c("shinycoreci", shinyverse_pkgs)
  )

  apps_deps_txt <- utils::capture.output(dput(apps_deps))

  cat(
    file = file.path(repo_dir, "R/data-apps-deps.R"),
    sep = "",
    "# Do not edit by hand!\n",
    "# This file is automatically generated by `./inst/gha/data-apps-deps-update.R`\n",
    "apps_deps <- ", paste0(apps_deps_txt, collapse = "\n"), "\n"
  )
}

base_packages <- function() {
  pkg_df <- as.data.frame(utils::installed.packages(), stringsAsFactors = FALSE)
  pkg_df$Package[pkg_df$Priority %in% c("base", "recommended")]
}
