library(shinytest2)

test_that("Migrated shinytest test: mytest.R", {
  app <- AppDriver$new(variant = shinytest2::platform_variant(),
    seed = 100, shiny_args = list(display.mode = "normal"))

  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(dataset = "pressure")
  app$set_inputs(update = "click")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(dataset = "cars")
  app$expect_values()
  app$expect_screenshot()
  app$set_inputs(dataset = "pressure")
  app$set_inputs(update = "click")
  app$set_inputs(obs = 11)
  app$set_inputs(obs = 12)
  app$set_inputs(update = "click")
  app$set_inputs(obs = 15)
  app$set_inputs(obs = 14)
  app$set_inputs(obs = 3)
  app$set_inputs(obs = 2)
  app$set_inputs(obs = 1)
  app$set_inputs(obs = 0)
  app$set_inputs(update = "click")
  app$expect_values()
  app$expect_screenshot()
})
