library(shinytest2)

test_that("Migrated shinytest test: mytest.R", {
  skip("(LEGACY) This app has issues about a URL being loaded. Testing manually instead.")

  app <- AppDriver$new(load_timeout = 15000, seed = 100, shiny_args = list(display.mode = "normal"))
  print(app$get_logs())
  cat('\n\n')
  print(app$get_logs())
  cat('\n\n')
  app$expect_download("download")
  print(app$get_logs())
  cat('\n\n')
  app$set_inputs(throw = TRUE)
  print(app$get_logs())
  cat('\n\n')
  app$expect_download("download")
  print(app$get_logs())
  cat('\n\n')
  Sys.sleep(4)
  app$expect_values()
  app$expect_screenshot()
  print(app$get_logs())
  cat('\n\n')
})
