# Do not edit by hand!
# This file is automatically generated by `./inst/gha/data-apps-deps-update.R`
shinyverse_pkgs <- c("shinycoreci", "cachem", "fastmap", "later", "bslib", "bsicons", 
"htmlwidgets", "crosstalk", "gt", "DT", "dygraphs", "flexdashboard", 
"fontawesome", "htmltools", "httpuv", "leaflet", "pool", "promises", 
"reactlog", "sass", "shiny", "shinymeta", "shinytest", "chromote", 
"shinytest2", "shinythemes", "shinyvalidate", "thematic", "webdriver", 
"websocket", "plotly", "shinyjster")

shinyverse_urls <- c("https://github.com/rstudio/shinycoreci", "https://github.com/r-lib/cachem", 
"https://github.com/r-lib/fastmap", "https://github.com/r-lib/later", 
"https://github.com/rstudio/bslib", "https://github.com/rstudio/bsicons", 
"https://github.com/ramnathv/htmlwidgets", "https://github.com/rstudio/crosstalk", 
"https://github.com/rstudio/gt", "https://github.com/rstudio/DT", 
"https://github.com/rstudio/dygraphs", "https://github.com/rstudio/flexdashboard", 
"https://github.com/rstudio/fontawesome", "https://github.com/rstudio/htmltools", 
"https://github.com/rstudio/httpuv", "https://github.com/rstudio/leaflet", 
"https://github.com/rstudio/pool", "https://github.com/rstudio/promises", 
"https://github.com/rstudio/reactlog", "https://github.com/rstudio/sass", 
"https://github.com/rstudio/shiny", "https://github.com/rstudio/shinymeta", 
"https://github.com/rstudio/shinytest", "https://github.com/rstudio/chromote", 
"https://github.com/rstudio/shinytest2", "https://github.com/rstudio/shinythemes", 
"https://github.com/rstudio/shinyvalidate", "https://github.com/rstudio/thematic", 
"https://github.com/rstudio/webdriver", "https://github.com/rstudio/websocket", 
"https://github.com/ropensci/plotly", "https://github.com/schloerke/shinyjster"
)
