# Do not edit by hand!
# This file is automatically generated by `./inst/gha/data-apps-deps-update.R`
# To add / update a package, make a PR here: https://github.com/posit-dev-shinycoreci/posit-dev-shinycoreci.r-universe.dev/blob/main/packages.json
shinyverse_cran_url <- "https://posit-dev-shinycoreci.r-universe.dev"

shinyverse_pkgs <- c("bsicons", "bslib", "cachem", "chromote", "crosstalk", "DT", 
"dygraphs", "fastmap", "flexdashboard", "fontawesome", "future", 
"gt", "htmltools", "htmlwidgets", "httpuv", "later", "leaflet", 
"plotly", "pool", "promises", "reactlog", "sass", "shiny", "shinycoreci", 
"shinyjster", "shinymeta", "shinytest", "shinytest2", "shinythemes", 
"shinyvalidate", "thematic", "webdriver", "websocket")

shinyverse_urls <- c("https://github.com/rstudio/bsicons", "https://github.com/rstudio/bslib", 
"https://github.com/r-lib/cachem", "https://github.com/rstudio/chromote", 
"https://github.com/rstudio/crosstalk", "https://github.com/rstudio/DT", 
"https://github.com/rstudio/dygraphs", "https://github.com/r-lib/fastmap", 
"https://github.com/rstudio/flexdashboard", "https://github.com/rstudio/fontawesome", 
"https://github.com/futureverse/future", "https://github.com/rstudio/gt", 
"https://github.com/rstudio/htmltools", "https://github.com/ramnathv/htmlwidgets", 
"https://github.com/rstudio/httpuv", "https://github.com/r-lib/later", 
"https://github.com/rstudio/leaflet", "https://github.com/ropensci/plotly", 
"https://github.com/rstudio/pool", "https://github.com/rstudio/promises", 
"https://github.com/rstudio/reactlog", "https://github.com/rstudio/sass", 
"https://github.com/rstudio/shiny", "https://github.com/rstudio/shinycoreci", 
"https://github.com/schloerke/shinyjster", "https://github.com/rstudio/shinymeta", 
"https://github.com/rstudio/shinytest", "https://github.com/rstudio/shinytest2", 
"https://github.com/rstudio/shinythemes", "https://github.com/rstudio/shinyvalidate", 
"https://github.com/rstudio/thematic", "https://github.com/rstudio/webdriver", 
"https://github.com/rstudio/websocket")
