update_renv_pkgs <- function() {
  renv_pkgs <- sort(unique(renv::dependencies(
    system.file(package = "shinycoreci", "apps"),
    progress = TRUE
  )$Package))

  renv_pkgs <- setdiff(
    renv_pkgs,
    base_packages()
  )

  renv_pkgs_txt <- capture.output(dput(renv_pkgs))

  cat(
    file = system.file(package = "shinycoreci", "R/data-renv-pkgs.R"),
    sep = "",
    "# Do not edit by hand!\n",
    "# This file is automatically generated by `./R/data-renv-pkgs-update.R`\n",
    "renv_pkgs <- ", paste0(renv_pkgs_txt, collapse = ""), "\n"
  )
}

base_packages <- function() {
  pkg_df <- as.data.frame(utils::installed.packages(), stringsAsFactors = FALSE)
  pkg_df$Package[pkg_df$Priority %in% c("base", "recommended")]
}
