# Do not edit by hand!
# This file is automatically generated by `./inst/gha/data-apps-deps-update.R`
apps_deps <- c("base64enc", "bslib", "Cairo", "clipr", "curl", "dbplyr", "DiagrammeR", 
"dplyr", "DT", "evaluate", "flexdashboard", "future", "ggplot2", 
"ggvis", "hexbin", "highcharter", "htmltools", "htmlwidgets", 
"httpuv", "jsonlite", "knitr", "later", "leaflet", "magrittr", 
"maps", "markdown", "memoise", "networkD3", "plotly", "png", 
"progress", "promises", "pryr", "radiant", "ragg", "RColorBrewer", 
"reactable", "reactlog", "reactR", "readr", "rlang", "rmarkdown", 
"rprojroot", "rsconnect", "RSQLite", "rversions", "scales", "sf", 
"shiny", "shinyAce", "shinydashboard", "shinyjs", "shinyjster", 
"shinymeta", "shinytest2", "shinythemes", "shinyvalidate", "showtext", 
"sysfonts", "systemfonts", "testthat", "thematic", "tidyr", "tm", 
"websocket", "withr", "wordcloud")
