# Used in GHA
update_connect_urls <- function(
  apps = TRUE,
  account = "barret",
  server = "beta.rstudioconnect.com"
) {

  urls <- connect_urls(apps = apps, account = account, server = server)

  urls_txt <- capture.output(dput(urls))

  cat(
    file = system.file(package = "shinycoreci", "R/data-connect-urls.R"),
    sep = "",
    "# Do not edit by hand!\n",
    "# This file is automatically generated by `./R/data-connect-urls-update.R`\n",
    "default_connect_urls <- ", paste0(urls_txt, collapse = ""), "\n"
  )
}
