update_connect_urls <- function() {

  urls <- connect_urls()

  urls_txt <- capture.output(dput(urls))

  cat(
    file = system.file(package = "shinycoreci", "R/data-connect-urls.R"),
    sep = "",
    "# Do not edit by hand!\n",
    "# This file is automatically generated by `./R/data-connect-urls-update.R`\n",
    "default_connect_urls <- ", paste0(urls_txt, collapse = ""), "\n"
  )
}
