# Do not edit by hand!
# This file is automatically generated by `./inst/gha/data-apps-deps-update.R`
apps_deps <- c("base64enc", "Cairo", "clipr", "curl", "dbplyr", "DiagrammeR", 
"dplyr", "evaluate", "future", "ggplot2", "ggvis", "hexbin", 
"highcharter", "htmlwidgets", "jsonlite", "knitr", "magrittr", 
"maps", "markdown", "memoise", "networkD3", "plotly", "png", 
"progress", "pryr", "radiant", "ragg", "RColorBrewer", "reactable", 
"reactR", "rlang", "rmarkdown", "rprojroot", "rsconnect", "RSQLite", 
"rversions", "scales", "sf", "shinyAce", "shinydashboard", "shinyjs", 
"showtext", "sysfonts", "systemfonts", "testthat", "tidyr", "tm", 
"withr", "wordcloud")
