# Do not edit by hand!
# This file is automatically generated by `./inst/gha/data-apps-deps-update.R`
apps_deps <- c("base64enc", "Cairo", "clipr", "curl", "dbplyr", "DiagrammeR", 
"dplyr", "evaluate", "future", "ggplot2", "ggvis", "hexbin", 
"highcharter", "htmlwidgets", "jsonlite", "knitr", "magrittr", 
"maps", "markdown", "memoise", "networkD3", "plotly", "png", 
"progress", "pryr", "radiant", "ragg", "RColorBrewer", "reactable", 
"reactR", "rlang", "rmarkdown", "rprojroot", "rsconnect", "RSQLite", 
"rversions", "scales", "sf", "shinyAce", "shinydashboard", "shinyjs", 
"showtext", "sysfonts", "systemfonts", "testthat", "tidyr", "tm", 
"withr", "wordcloud")
apps_deps_map <- list(`001-hello` = "rsconnect", `012-datatables` = "ggplot2", 
    `016-knitr-pdf` = "rmarkdown", `020-knit-html` = c("evaluate", 
    "knitr", "rmarkdown"), `021-selectize-plot` = "maps", `022-unicode-chinese` = c("curl", 
    "showtext", "sysfonts"), `026-shiny-inline` = "rmarkdown", 
    `027-absolutely-positioned-panels` = "markdown", `047-image-output` = "png", 
    `048-including-html-text-and-markdown-files` = "markdown", 
    `051-movie-explorer` = c("dbplyr", "dplyr", "ggvis", "RSQLite"
    ), `063-superzip-example` = c("dplyr", "RColorBrewer", "scales"
    ), `082-word-cloud` = c("memoise", "tm", "wordcloud"), `093-plot-interaction-basic` = "ggplot2", 
    `094-image-interaction-basic` = "png", `095-plot-interaction-advanced` = c("ggplot2", 
    "scales"), `099-plot-interaction-article-4` = "ggplot2", 
    `101-plot-interaction-article-6` = "ggplot2", `102-plot-interaction-article-7` = "ggplot2", 
    `103-plot-interaction-article-8` = "ggplot2", `104-plot-interaction-select` = "ggplot2", 
    `105-plot-interaction-zoom` = "ggplot2", `106-plot-interaction-exclude` = "ggplot2", 
    `108-module-output` = c("dplyr", "ggplot2"), `112-generate-report` = "rmarkdown", 
    `118-highcharter-births` = c("dplyr", "highcharter", "tidyr"
    ), `121-async-timer` = c("future", "magrittr"), `122-async-outputs` = "future", 
    `123-async-renderprint` = "future", `124-async-download` = "future", 
    `125-async-req` = "future", `126-async-ticks` = "future", 
    `129-async-perf` = c("future", "ggplot2"), `140-selectize-inputs` = "jsonlite", 
    `141-radiant` = "radiant", `143-async-plot-caching` = "ggplot2", 
    `147-websocket` = "shinyjs", `149-onRender` = c("htmlwidgets", 
    "plotly"), `150-networkD3-sankey` = c("networkD3", "shinydashboard"
    ), `151-reactr-input` = "reactR", `153-connection-header` = c("curl", 
    "future"), `156-subapps` = "rmarkdown", `161-discrete-limits` = c("dplyr", 
    "ggplot2"), `168-supporting-r-dir` = "withr", `169-prerender` = "rmarkdown", 
    `173-invalidatelater-leak` = "pryr", `174-throttle-debounce` = "magrittr", 
    `178-delayed-widget` = "htmlwidgets", `179-nondelayed-widget` = "htmlwidgets", 
    `180-delayed-staticwidget` = "htmlwidgets", `181-report-image` = c("Cairo", 
    "jsonlite", "ragg", "showtext", "sysfonts", "systemfonts"
    ), `182-report-png` = c("Cairo", "jsonlite", "ragg", "showtext", 
    "sysfonts", "systemfonts"), `183-report-cairo` = c("Cairo", 
    "jsonlite", "ragg", "showtext", "sysfonts", "systemfonts"
    ), `184-report-ragg` = c("Cairo", "jsonlite", "ragg", "showtext", 
    "sysfonts", "systemfonts"), `185-report-theme` = c("Cairo", 
    "jsonlite", "knitr", "ragg", "rmarkdown"), `193-reactlog-dynamic-ui` = "rversions", 
    `200-flexdashboard-render-text` = c("knitr", "plotly", "rmarkdown"
    ), `205-dynamic-tabs-compat` = "withr", `206-freeze-thaw` = "rlang", 
    `208-bind-cache-event` = "magrittr", `209-datepicker` = c("jsonlite", 
    "magrittr", "rlang"), `210-future_promise` = c("future", 
    "magrittr", "shinyjs"), `211-sv-custom-inputs` = "base64enc", 
    `212-daterangepicker` = "jsonlite", `212-shinymeta` = c("clipr", 
    "dplyr", "plotly", "shinyAce"), `216-quosures` = c("DiagrammeR", 
    "rlang"), `217-snapshot-info-option` = c("jsonlite", "testthat"
    ), `217-snapshot-info-url` = c("jsonlite", "testthat"), `300-bs-themer` = c("curl", 
    "ggplot2", "hexbin", "knitr", "reactable", "rlang", "rprojroot", 
    "rsconnect"), `301-bs-themes` = c("ggplot2", "rversions", 
    "sf", "withr"), `302-bootswatch-themes` = c("ggplot2", "progress", 
    "rversions", "sf", "withr"))
