on:
  workflow_call:

name: Pre checks

jobs:
  config:
    name: Pre checks
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Pull
        uses: actions/checkout@v4

      - name: Validate testing files
        run: python -u inst/gha/validate-test-files.py

      - name: Collect changed file names
        if: github.event_name == 'pull_request'
        id: files_changed
        uses: Ana06/get-changed-files@v2.3.0
        with:
          format: "json"
          filter: "*"

      - name: Validate >= 1 Shiny app file is altered
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          # It is possible that a file contains a space, use json to parse the array
          readarray -t FILES_CHANGED <<<"$(jq -r '.[]' <<<'${{ steps.files_changed.outputs.all }}')"
          # maintain that the file names are quoted by using [@]
          echo Files modified or changed: $FILES_CHANGED
          for FIL in ${FILES_CHANGED[@]}; do
            echo "Inspecting file: '$FIL'"
            # check if path is in apps
            if [[ "$FIL" =~ ^".github" ]]; then
              echo '.github folder was altered. Returning early'
              exit 0
            fi
            if [[ "$FIL" =~ ^"inst/apps" ]]; then
              SUBFIL=$(echo "$FIL" | cut -d/ -f 1-2)
              echo "first two folders of file: '$SUBFIL'"
              if [ -d "$SUBFIL" ]; then
                echo 'At least 1 Shiny app folder was altered. Returning early'
                exit 0
              fi
            fi
          done
          echo 'No apps folders added or modified'
          exit 1
